# 项目相关配置
ruoyi:
  # 文件上传路径
  profile: D:/profile/

# 测试环境配置
server:
  # 服务端口
  port: 8081

#数据源配置
spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://test:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
        username: root
        password: password
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password: